version: '2'
services:
  web:
    working_dir: /app
    build: .
    volumes:
      - "./:/app"
    command: bash -c 'bundle exec falcon serve -p 3000 -b "http://0.0.0.0"'
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - redis
    links:
      - postgres:postgres
      - redis:redis
  postgres:
    image: postgres:9.4
    volumes:
      - ./.data/postgres:/var/lib/postgresql/data
  redis:
    image: redis
    volumes:
      - ./.data/redis:/data
